repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
      exclude: ^helm-chart/
      stages: [commit]
    - id: check-toml
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    - id: check-case-conflict
      stages: [commit]
    - id: detect-private-key
      stages: [commit]
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.1.2
    hooks:
    - id: typos
      exclude: ^migrations/
      stages: [commit]
  - repo: https://github.com/crate-ci/committed
    rev: v0.2.5
    hooks:
    - id: committed
      stages: [commit-msg]

