version: "3.9"

services:
  rest:
    build: .
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8080:8080
    restart: always
    networks:
      - mup-network

  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db-data/:/var/lib/postgresql/data/
    networks:
      - mup-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mup-network

networks:
  mup-network:
